import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import type { AggregatedMetric, Report } from "@ohmyperf/core";

export const REPORTER_ID = "markdown" as const;

export interface MarkdownReporterOptions {
  readonly fileName?: string;
  readonly title?: string;
  readonly includePluginData?: boolean;
}

export interface MarkdownReporterResult {
  readonly path: string;
  readonly bytes: number;
}

const HEADLINE_METRICS = ["lcp", "fcp", "ttfb", "inp", "cls", "tbt"] as const;
const UNSTABLE_COV_THRESHOLD = 0.2;

export async function writeMarkdownReport(
  report: Report,
  outputDir: string,
  opts: MarkdownReporterOptions = {},
): Promise<MarkdownReporterResult> {
  const dir = resolve(outputDir);
  const fileName = opts.fileName ?? "report.md";
  const path = join(dir, fileName);
  await mkdir(dirname(path), { recursive: true });
  const body = renderMarkdown(report, opts);
  await writeFile(path, body, "utf8");
  return { path, bytes: Buffer.byteLength(body) };
}

export function renderMarkdown(report: Report, opts: MarkdownReporterOptions = {}): string {
  const title = opts.title ?? "OhMyPerf report";
  const lines: string[] = [];
  lines.push(`## ${title}`);
  lines.push("");
  lines.push(`- **URL**: \`${report.meta.url}\``);
  lines.push(
    `- **Mode**: \`${report.meta.mode}\` · **Runs**: ${String(report.meta.runs)} · **Headless**: \`${report.meta.parity.mode}\``,
  );
  lines.push(
    `- **Browser**: \`${report.meta.browser.name} ${report.meta.browser.version}\` (${report.meta.browser.source})`,
  );
  if (report.meta.calibration) {
    lines.push(
      `- **Calibration**: throttle ${report.meta.calibration.throttleRate}× · ${report.meta.calibration.networkProfile}` +
        (report.meta.calibration.cacheHit ? " · cached" : ""),
    );
  }
  if (report.meta.unstable) {
    lines.push(`- ⚠️ **Unstable run** — at least one CWV has CoV > 20%.`);
  }
  lines.push("");

  lines.push("### Core Web Vitals");
  lines.push("");
  lines.push("| Metric | Median | p75 | p95 | CoV | n |");
  lines.push("|--------|-------:|----:|----:|----:|---:|");
  for (const name of HEADLINE_METRICS) {
    const agg = report.aggregated[name];
    if (!agg) continue;
    lines.push(formatAggregatedRow(name, agg));
  }
  lines.push("");

  if (report.audits.length > 0) {
    lines.push("### Audits");
    lines.push("");
    lines.push("| Status | ID | Title |");
    lines.push("|--------|----|-------|");
    for (const a of report.audits) {
      const status = a.passed ? "✅ PASS" : "❌ FAIL";
      lines.push(
        `| ${status} | \`${escapeMd(a.id)}\` | ${escapeMd(a.title)} |`,
      );
    }
    lines.push("");
  }

  const sourceRun = report.runs.find((r) => !r.cold) ?? report.runs[0];
  if (sourceRun && sourceRun.resources.length > 0) {
    const totalBytes = sourceRun.resources.reduce((acc, r) => acc + (r.encodedSizeBytes || 0), 0);
    const renderBlocking = sourceRun.resources.filter((r) => r.renderBlocking).length;
    lines.push("### Resources");
    lines.push("");
    lines.push(
      `- ${String(sourceRun.resources.length)} resources · ${formatBytes(totalBytes)} total${
        renderBlocking > 0 ? ` · ${String(renderBlocking)} render-blocking` : ""
      }`,
    );
    lines.push("");
  }

  if (opts.includePluginData) {
    const keys = Object.keys(report.pluginData);
    if (keys.length > 0) {
      lines.push("### Plugin data");
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>Show JSON</summary>");
      lines.push("");
      lines.push("```json");
      lines.push(JSON.stringify(report.pluginData, null, 2));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  }

  lines.push(`<sub>Generated by OhMyPerf v${report.schemaVersion} · ${report.meta.measurementId}</sub>`);
  lines.push("");
  return lines.join("\n");
}

function formatAggregatedRow(name: string, agg: AggregatedMetric): string {
  const digits = name === "cls" ? 3 : 1;
  const median = formatValue(agg.median, name, digits);
  const p75 = formatValue(agg.p75, name, digits);
  const p95 = formatValue(agg.p95, name, digits);
  const covPct = (agg.cov * 100).toFixed(1) + "%";
  const unstableMark = agg.cov > UNSTABLE_COV_THRESHOLD ? " ⚠️" : "";
  return `| **${name.toUpperCase()}** | ${median} | ${p75} | ${p95} | ${covPct}${unstableMark} | ${String(agg.runs)} |`;
}

function formatValue(value: number, name: string, digits: number): string {
  if (!Number.isFinite(value)) return "—";
  if (name === "cls") return value.toFixed(digits);
  return `${value.toFixed(digits)} ms`;
}

function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 B";
  if (bytes < 1024) return `${String(Math.round(bytes))} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

function escapeMd(s: string): string {
  return s.replace(/[|\\`]/g, (ch) => `\\${ch}`);
}
